### PR TITLE
build(deps): remove old node-forge

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Review by martinmaillard — APPROVED** [review]

**Comment by tpluscode** [comment]
@martinmaillard do you know why the e2e fail? I tried locally but I was having issues starting cypress

**Comment by martinmaillard** [comment]
No I don't know. I'm trying to understand, but it's really hard to debug and the videos are not helping at all.

**Comment by martinmaillard** [comment]
The API request to create a project is actually failing
Screenshot 2022-04-12 at 09 49 30
Screenshot 2022-04-12 at 09 49 42

It's also failing locally for me

**Comment by tpluscode** [comment]
Ok, that's something, thanks. Don't know why cypress stopped working for me

**Pull request merged**
