### PR TITLE
fix(ui): memoize API documentation

### PR DESCRIPTION
**Pull request by martinmaillard**
I applied the same hack that we did in the first project. @tpluscode let me know if there's a better way.

### CODE REVIEW

**Comment by tpluscode** [comment]
`Hydra.cacheStrategy.shouldLoad` is a bool function hook which lets you decide if previously loaded resource should be returned without hitting the API

```typescript
Hydra.cacheStrategy.shouldLoad = (previous) => {
  return previous.representation.root?.types.has(hydra.ApiDocumentation)
}
```

**Comment by martinmaillard** [comment]
Nice, done

**Comment by tpluscode** [comment]
The failed cypress test is just a fluke?

**Comment by martinmaillard** [comment]
I don't understand why:
1. We have a test run for "push" *and* one for "pull_request"
2. One of the two sometimes fails when the other one doesn't

**Pull request merged**
