### PR TITLE
chore: upgrade some dependencies

### PR DESCRIPTION
**Pull request by martinmaillard**

### CODE REVIEW

**Comment by tpluscode** [comment]
You wanna `npx yarn-deduplicate`

Might even add that as `postinstall` script

**Comment by l00mi** [comment]
Why did this not create a "Merge to Release" PR?

**Comment by tpluscode** [comment]
Because there is no changeset file. Ie. nothing significant for the consumer (users)

**Comment by l00mi** [comment]
ack, okay for integ, and for prod it will need manual deployment anyhow.

**Pull request merged**
