### PR TITLE
API redirects text/html requests to UI

### PR DESCRIPTION
**Pull request by vhf**

### CODE REVIEW

**Review by tpluscode — APPROVED** [review]

**Review by martinmaillard — APPROVED** [review]
Looks good to me.

One thing I couldn't figure out: where is the `/app` route defined?

**Comment by tpluscode** [comment]
Well it's not. This will apply only to the deployed instance where `/app` is the UI running its own container

**Comment by martinmaillard** [comment]
Ok but where is the redirection defined? Do we have a proxy in front of the API & App?

**Comment by tpluscode** [comment]
> Ok but where is the redirection defined? Do we have a proxy in front of the API & App?

@sandhose ☝️

**Comment by sandhose** [comment]
> > Ok but where is the redirection defined? Do we have a proxy in front of the API & App?
> 
> @sandhose ☝️

@tpluscode @martinmaillard There is `ingress-nginx` running in front that handles all HTTP traffic in the cluster, which consumes Ingress resources. In particular, routing for this app is done here: https://gitlab.ldbar.ch/vshn/gitops-prod/-/blob/master/zazuko/test/cube-creator/ingress.yaml

**Pull request merged**
