### PR TITLE
Store and display shacl report on publication jobs

### PR DESCRIPTION
**Pull request by martinmaillard**
Part of #1018

### CODE REVIEW

**Comment by martinmaillard** [comment]
I'm not exactly sure why the tests are timing out. Data looks correct to me, but it seems like the validation is not detecting the `cube:observationConstraint`. Even if the data is not valid, I don't know why the job is running forever.

**Comment by martinmaillard** [comment]
It also runs forever locally. No error, nothing. Not sure how to debug this.

**Comment by martinmaillard** [comment]
Gosh, e2e are failing for some reason, but they are passing locally. I hate this...

**Comment by martinmaillard** [comment]
@tpluscode Do you think we can merge this?

**Comment by tpluscode** [comment]
Yes, let's do it

**Pull request merged**
