### PR TITLE
fix: dcterms:identifier validation error

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by martinmaillard** [comment]
I think `dcterms:identifier` is still needed by the CKAN harvester endpoint. Is it populated on publication using the one from the project?

**Comment by tpluscode** [comment]
Yes, hence validation errors. If they got out of sync, the resulting cube would have 2 values.

I figure there is no point in duplicating them anyway

**Review by martinmaillard — APPROVED** [review]

**Comment by l00mi** [comment]
Do I get this correct that is making a clone in the UI vs making a clone in publishing.

My question then, how could the UI clone get out of sync then? Should it not always be changed immediately?

**Comment by tpluscode** [comment]
I don't follow. What clone?

**Pull request merged**
